version: '3.7'
services:
  mongo0:
    image: diaaahmed/mongo-enterprise:4.2
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--dbpath", "/data", "--journal", "--bind_ip_all", "--enableEncryption", "--encryptionKeyFile", "/data/mongodb.key" ]
    restart: always
    volumes:
    - "./scripts/:/data/"

  mongo1:
    image: diaaahmed/mongo-enterprise:4.2
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--journal", "--bind_ip_all", "--enableEncryption", "--encryptionKeyFile", "/data/mongodb.key" ]
    restart: always
    volumes:
    - "./scripts/file.key:/data/file.key"
    - "./scripts/mongodb.key:/data/mongodb.key"

  mongo2:
    image: diaaahmed/mongo-enterprise:4.2
    command: bash -c "/usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all --enableEncryption --encryptionKeyFile /data/mongodb.key" 
    restart: always
    volumes:
    - "./scripts/file.key:/data/file.key"
    - "./scripts/mongodb.key:/data/mongodb.key"
